name: Security Scan

on: 
  pull_request: 
    branches: [master]
    types: [opened, synchronize]

jobs: 
  checkov:
    uses: clouddrove/github-shared-workflows/.github/workflows/checkov.yml@62909fc10e105bba5cba4ff73b03c020b97789d4 # pinned to latest
    with:
      directory: '.'
      continue_on_error: 'true'
      skip_check: 'CKV_TF_1'