name: Tag Release

on:
  pull_request:
    types: [closed]

jobs: 
  release:
    uses: clouddrove/github-shared-workflows/.github/workflows/tag-release.yml@c615ea7ef3e5beba98a335bf9acce8e67e03c755 # pinned to latest
    with:
      target_branch: master
    secrets:
      GITHUB: ${{ secrets.GITHUB_TOKEN }}